### ISSUE TITLE
request.getCallback() is not a existing method

### ISSUE THREAD

**Issue by ghost** [mlieshoff/brawljars#26]
![grafik](https://user-images.githubusercontent.com/74135012/125143213-418b9c80-e11a-11eb-981a-37f172c557d4.png)

**Comment by ghost** [comment]
@mlieshoff, are you still working/contributing on/to this project?

**Comment by mlieshoff** [comment]
@jannpaechnatz Hey Jann, yes its still supported, sorry for answering late... The issue is about *lombok*, so you can go to Settings/Build, Execution, Deployment/Compiler/Annotation Processors/ -> Enable Annotation Processing (check this checkbox)

**Comment by ghost** [comment]
> @jannpaechnatz Hey Jann, yes its still supported, sorry for answering late... The issue is about *lombok*, so you can go to Settings/Build, Execution, Deployment/Compiler/Annotation Processors/ -> Enable Annotation Processing (check this checkbox)

thanks I enjoy your api very much
